### ISSUE TITLE
Function Menu modules outdated

### ISSUE THREAD

**Issue by cweiske** [TYPO3-Documentation/TYPO3CMS-Reference-InsideTypo3#2]
`Documentation/CoreArchitecture/BackendModules/FunctionMenuModules/Index.rst` gives 4.x class names instead of 6.2 class names (e.g. `t3lib_extMgm::extPath` and `t3lib_extobjbase`)

**Comment by fsuter** [comment]
Inside TYPO3 is dramatically out of date. You're right about the need to fix this, but it's really the whole manual that needs to be overhauled and this is currently (and sadly) beyond the Documentation Team's manpower.

**Comment by Chrissitopher** [comment]
Fixed with https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-InsideTypo3/commit/be6b7024325706acabbf410daba1cf31389b7177.
