### ISSUE TITLE
Add infos about symfony commands and add info about deprecated cli_dispatch.phpsh

### ISSUE THREAD

**Issue by josefglatz** [TYPO3-Documentation/TYPO3CMS-Reference-InsideTypo3#20]
https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-InsideTypo3/edit/latest/Documentation/CoreArchitecture/BackendModules/CliScripts/Index.rst

**Comment by josefglatz** [comment]
Should something like that going into this manual? Or do wo should move something like that to Core API?

**Comment by susannemoog** [comment]
Symfony commands are now documented in that chapter. Can we close this ticket?
