### ISSUE TITLE
Update description of bootstrap classes

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-InsideTypo3#38]
https://docs.typo3.org/typo3cms/InsideTypo3Reference/CoreArchitecture/Backend/Initialization/Index.html

Description seems to be accurately covering 8.7 code, but some of the functions are not in the Bootstrap class (as described) they are in the Application classes implementing ApplicationInterface:

- bullet point 9: Bootstrap::run() is not in Bootstrap, run is in the classes implementing ApplicationInterface (e.g. TYPO3\CMS\Backend\Http\BackendApplication)
- bullet point 1 : defineLegacyConstants(), is not in Bootstrap, it's in Application*

Probably wouldn't hurt to update it.

I can make a PR, but will a wait a few days, in case someone has some thoughts on this.

**Comment by marble** [comment]
Sounds great. You can safely create a PR. Chances are very tiny somebody else does it.

**Comment by sypets** [comment]
ok :)

**Comment by sypets** [comment]
Done
